package main

import (
	"encoding/json"
	"encoding/xml"
	"flag"
	"fmt"
	"os"
	"regexp"
	"strconv"
	"strings"
)

func toPascalCase(s string) string {
	re := regexp.MustCompile(`[_\-\s]+`)
	parts := re.Split(s, -1)
	var result []string
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		result = append(result, strings.ToUpper(p[:1])+strings.ToLower(p[1:]))
	}
	return strings.Join(result, "")
}

func isValidIdentifier(s string) bool {
	re := regexp.MustCompile(`^[a-zA-Z_$][a-zA-Z0-9_$]*$`)
	return re.MatchString(s)
}

func inferType(v string) string {
	v = strings.TrimSpace(v)
	if v == "" {
		return "string"
	}

	lower := strings.ToLower(v)
	if lower == "true" || lower == "false" {
		return "boolean"
	}

	if _, err := strconv.Atoi(v); err == nil {
		return "number"
	}

	if _, err := strconv.ParseFloat(v, 64); err == nil {
		return "number"
	}

	trimmed := strings.TrimSpace(v)
	if (len(trimmed) >= 2 && trimmed[0] == '{' && trimmed[len(trimmed)-1] == '}') ||
		(len(trimmed) >= 2 && trimmed[0] == '[' && trimmed[len(trimmed)-1] == ']') {
		var js interface{}
		if json.Unmarshal([]byte(trimmed), &js) == nil {
			return "any"
		}
	}

	return "string"
}

// xmlNode represents an XML element in our tree.
type xmlNode struct {
	name     string
	text     string
	attrs    map[string]string
	children []*xmlNode
}

// nodeInfo holds type information for TypeScript generation.
type nodeInfo struct {
	name   string
	fields map[string]string
}

// parseXMLTree builds an xmlNode tree from XML data.
func parseXMLTree(data []byte) (*xmlNode, error) {
	decoder := xml.NewDecoder(strings.NewReader(string(data)))
	var root *xmlNode
	var current *xmlNode

	for {
		token, err := decoder.Token()
		if err != nil {
			break
		}

		switch t := token.(type) {
		case xml.StartElement:
			node := &xmlNode{
				name:    t.Name.Local,
				attrs:   make(map[string]string),
			}
			for _, attr := range t.Attr {
				attrName := attr.Name.Local
				if attrName != "" {
					node.attrs[attrName] = attr.Value
				}
			}

			if root == nil {
				root = node
				current = node
			} else if current != nil {
				current.children = append(current.children, node)
				current = node
			}

		case xml.EndElement:
			// Go back to parent
			if current == root {
				return root, nil
			}
			for _, child := range root.children {
				if child == current {
					// Already handled
				}
			}
			// Walk back up - find parent
			stack := []*xmlNode{root}
			for len(stack) > 0 {
				top := stack[len(stack)-1]
				if top == current {
					stack = stack[:len(stack)-1]
					current = top
					break
				}
				if len(top.children) > 0 {
					stack = append(stack, top.children[len(top.children)-1])
				}
			}
			if len(stack) == 0 {
				current = root
			}

		case xml.CharData:
			if current != nil {
				current.text += string(t)
			}
		}
	}

	return root, nil
}

func main() {
	inputFlag := flag.String("i", "", "input XML file (default: stdin)")
	outputFlag := flag.String("o", "", "output .ts file (default: stdout)")
	nameFlag := flag.String("n", "Root", "root interface name")
	flag.Parse()

	var data []byte
	var err error

	if *inputFlag != "" {
		data, err = os.ReadFile(*inputFlag)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error reading file: %v\n", err)
			os.Exit(1)
		}
	} else {
		buf := make([]byte, 0, 4096)
		for {
			header := make([]byte, 4096)
			n, e := os.Stdin.Read(header)
			buf = append(buf, header[:n]...)
			if e != nil {
				break
			}
		}
		data = buf
	}

	if len(data) == 0 {
		fmt.Fprintf(os.Stderr, "Error: empty input\n")
		os.Exit(1)
	}

	root, err := parseXMLTree(data)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error parsing XML: %v\n", err)
		os.Exit(1)
	}

	if root == nil {
		fmt.Fprintf(os.Stderr, "Error: no XML element found\n")
		os.Exit(1)
	}

	ifName := *nameFlag
	if !isValidIdentifier(ifName) {
		ifName = toPascalCase(root.name)
		if ifName == "" {
			ifName = "Root"
		}
	}

	collected := make(map[string]*nodeInfo)
	analyzeNode(root, ifName, collected)

	var sb strings.Builder
	sb.WriteString("// Generated by xml-to-typescript\n")
	sb.WriteString("// Do not edit manually.\n\n")

	printed := make(map[string]bool)
	printOne(&sb, ifName, collected, printed)

	if *outputFlag != "" {
		err = os.WriteFile(*outputFlag, []byte(sb.String()), 0644)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Error writing file: %v\n", err)
			os.Exit(1)
		}
	} else {
		fmt.Print(sb.String())
	}
}

func analyzeNode(node *xmlNode, name string, collected map[string]*nodeInfo) {
	if collected[name] != nil {
		return
	}

	info := &nodeInfo{
		name:   name,
		fields: make(map[string]string),
	}
	collected[name] = info

	// Process attributes
	for attrName, attrVal := range node.attrs {
		info.fields[attrName] = inferType(attrVal)
	}

	// Group children by name
	childGroups := make(map[string][]*xmlNode)
	for _, child := range node.children {
		childGroups[child.name] = append(childGroups[child.name], child)
	}

	// Determine types for each child group
	for elemName, children := range childGroups {
		first := children[0]
		hasNested := len(first.children) > 0

		if hasNested {
			itemName := name + "_" + toPascalCase(elemName)
			analyzeNode(first, itemName, collected)

			if len(children) > 1 {
				info.fields[elemName] = itemName + "[]"
			} else {
				info.fields[elemName] = itemName
			}
		} else {
			// Leaf elements - collect text values
			var values []string
			for _, c := range children {
				values = append(values, strings.TrimSpace(c.text))
			}

			if len(values) > 1 {
				tsType := inferType(values[0])
				info.fields[elemName] = tsType + "[]"
			} else {
				tsType := inferType(values[0])
				info.fields[elemName] = tsType
			}
		}
	}

	// Text content if no children and has text
	if len(node.children) == 0 && len(info.fields) == 0 {
		text := strings.TrimSpace(node.text)
		if text != "" {
			info.fields["$value"] = inferType(text)
		}
	}
}

func printOne(sb *strings.Builder, name string, collected map[string]*nodeInfo, printed map[string]bool) {
	if printed[name] {
		return
	}
	printed[name] = true

	info := collected[name]
	if info == nil {
		return
	}

	// Print child interfaces first
	for _, typ := range info.fields {
		baseType := strings.TrimSuffix(typ, "[]")
		if collected[baseType] != nil && !printed[baseType] {
			printOne(sb, baseType, collected, printed)
		}
	}

	sb.WriteString(fmt.Sprintf("export interface %s {\n", name))

	var keys []string
	for k := range info.fields {
		keys = append(keys, k)
	}
	sortStrings(keys)

	for _, key := range keys {
		sb.WriteString(fmt.Sprintf("  \"%s\": %s;\n", key, info.fields[key]))
	}

	sb.WriteString("}\n\n")
}

func sortStrings(s []string) {
	for i := 0; i < len(s); i++ {
		for j := i + 1; j < len(s); j++ {
			if s[i] > s[j] {
				s[i], s[j] = s[j], s[i]
			}
		}
	}
}
