// env-to-script converts .env files to shell scripts with export statements.
//
// Usage:
//
//	env-to-script .env
//	env-to-script -f .env -o setup.sh -t bash
//	env-to-script -j .env
package main

import (
	"bufio"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"strings"
)

// Entry represents a single key=value pair from a .env file.
type Entry struct {
	Key   string
	Value string
}

func main() {
	var (
		inputPath    string
		outputPath   string
		scriptType   string
		exportPrefix bool
		singleQuotes bool
		escapeDollar bool
		jsonOutput   bool
	)

	flag.StringVar(&inputPath, "f", "", "Path to the .env file (or pass as positional arg)")
	flag.StringVar(&outputPath, "o", "", "Output file path (default: stdout)")
	flag.StringVar(&scriptType, "t", "sh", "Script type: sh, bash, zsh, fish, powershell")
	flag.BoolVar(&exportPrefix, "export", true, "Prefix variables with export (sh/bash/zsh only)")
	flag.BoolVar(&singleQuotes, "single", false, "Use single quotes instead of double quotes")
	flag.BoolVar(&escapeDollar, "escape", true, "Escape dollar signs in values")
	flag.BoolVar(&jsonOutput, "j", false, "Output as JSON instead of shell script")
	flag.Parse()

	if flag.NArg() > 0 {
		inputPath = flag.Args()[0]
	}

	if inputPath == "" {
		fmt.Fprintln(os.Stderr, "Error: input file required")
		fmt.Fprintln(os.Stderr, "Usage: env-to-script [-t bash] [-o output.sh] .env")
		os.Exit(1)
	}

	entries, err := parseEnv(inputPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}

	if len(entries) == 0 {
		fmt.Fprintln(os.Stderr, "Warning: no valid entries found in", inputPath)
		os.Exit(0)
	}

	var output strings.Builder
	if jsonOutput {
		data, _ := json.MarshalIndent(entries, "", "  ")
		output.Write(data)
		output.WriteString("\n")
	} else {
		switch scriptType {
		case "sh", "bash", "zsh":
			generateShell(&output, entries, scriptType, exportPrefix, singleQuotes, escapeDollar, inputPath)
		case "fish":
			generateFish(&output, entries, singleQuotes, escapeDollar, inputPath)
		case "powershell":
			generatePowerShell(&output, entries, inputPath)
		default:
			fmt.Fprintf(os.Stderr, "Error: unsupported script type %q (supported: sh, bash, zsh, fish, powershell)\n", scriptType)
			os.Exit(1)
		}
	}

	if outputPath != "" {
		if err := os.WriteFile(outputPath, []byte(output.String()), 0755); err != nil {
			fmt.Fprintf(os.Stderr, "Error writing %s: %v\n", outputPath, err)
			os.Exit(1)
		}
		fmt.Printf("Script written to %s (%d variables)\n", outputPath, len(entries))
	} else {
		fmt.Print(output.String())
	}
}

func parseEnv(path string) ([]Entry, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("opening %s: %w", path, err)
	}
	defer f.Close()

	var entries []Entry
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		line = strings.TrimPrefix(line, "export ")

		key, value, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}

		key = strings.TrimSpace(key)
		if key == "" || !isValidKey(key) {
			continue
		}

		value = trimQuotes(strings.TrimSpace(value))
		entries = append(entries, Entry{Key: key, Value: value})
	}

	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("reading %s: %w", path, err)
	}

	return entries, nil
}

func isValidKey(key string) bool {
	if len(key) == 0 {
		return false
	}
	for i, r := range key {
		if i == 0 {
			if !((r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') || r == '_') {
				return false
			}
		} else {
			if !((r >= 'A' && r <= 'Z') || (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') || r == '_') {
				return false
			}
		}
	}
	return true
}

func trimQuotes(s string) string {
	if len(s) >= 2 {
		if (s[0] == '"' && s[len(s)-1] == '"') || (s[0] == '\'' && s[len(s)-1] == '\'') {
			return s[1 : len(s)-1]
		}
	}
	return s
}

func generateShell(buf *strings.Builder, entries []Entry, scriptType string, exportPrefix, singleQuotes, escapeDollar bool, sourceFile string) {
	switch scriptType {
	case "bash":
		buf.WriteString("#!/usr/bin/env bash\n")
	case "zsh":
		buf.WriteString("#!/usr/bin/env zsh\n")
	default:
		buf.WriteString("#!/bin/sh\n")
	}

	buf.WriteString("# Auto-generated by env-to-script\n")
	buf.WriteString(fmt.Sprintf("# Source: %s\n", sourceFile))
	buf.WriteString("#\n")

	if scriptType == "bash" || scriptType == "zsh" {
		buf.WriteString("set -euo pipefail\n\n")
	} else {
		buf.WriteString("set -eu\n\n")
	}

	for _, e := range entries {
		if exportPrefix {
			buf.WriteString("export ")
		}
		buf.WriteString(e.Key)
		buf.WriteString("=")

		if singleQuotes {
			buf.WriteString("'")
			buf.WriteString(strings.ReplaceAll(e.Value, "'", "'\"'\"'"))
			buf.WriteString("'")
		} else {
			buf.WriteString("\"")
			buf.WriteString(escapeDoubleQuoted(e.Value, escapeDollar))
			buf.WriteString("\"")
		}
		buf.WriteString("\n")
	}
}

func escapeDoubleQuoted(v string, escapeDollar bool) string {
	v = strings.ReplaceAll(v, "\\", "\\\\")
	if escapeDollar {
		v = strings.ReplaceAll(v, "$", "\\$")
	}
	v = strings.ReplaceAll(v, "`", "\\`")
	v = strings.ReplaceAll(v, "\"", "\\\"")
	return v
}

func generateFish(buf *strings.Builder, entries []Entry, singleQuotes, escapeDollar bool, sourceFile string) {
	buf.WriteString("#!/usr/bin/env fish\n")
	buf.WriteString("# Auto-generated by env-to-script\n")
	buf.WriteString(fmt.Sprintf("# Source: %s\n\n", sourceFile))

	for _, e := range entries {
		buf.WriteString("set -gx ")
		buf.WriteString(e.Key)
		buf.WriteString(" ")

		if singleQuotes {
			buf.WriteString("'")
			buf.WriteString(strings.ReplaceAll(e.Value, "'", "'\"'\"'"))
			buf.WriteString("'")
		} else {
			buf.WriteString("\"")
			v := e.Value
			if escapeDollar {
				v = strings.ReplaceAll(v, "$", "\\$")
			}
			v = strings.ReplaceAll(v, "`", "\\`")
			v = strings.ReplaceAll(v, "\"", "\\\"")
			buf.WriteString(v)
			buf.WriteString("\"")
		}
		buf.WriteString("\n")
	}
}

func generatePowerShell(buf *strings.Builder, entries []Entry, sourceFile string) {
	buf.WriteString("# Auto-generated by env-to-script\n")
	buf.WriteString(fmt.Sprintf("# Source: %s\n", sourceFile))
	buf.WriteString("#Requires -Version 5.1\n\n")

	for _, e := range entries {
		buf.WriteString("Set-Item -Path env:")
		buf.WriteString(e.Key)
		buf.WriteString(" -Value '")
		buf.WriteString(strings.ReplaceAll(e.Value, "'", "''"))
		buf.WriteString("'\n")
	}
}
